#ifndef AKIT_CONSTANTS_H
#define AKIT_CONSTANTS_H
#define AKIT_SAMPLE_RATE 44100
#define AKIT_FRAME_LENGTH 512
#define AKIT_CHANNELS 2
#define AKIT_MAX_SOUNDS 24
#define AKIT_MAX_SOUND_LENGTH 60
#define AKIT_TAPE_LENGTH_MULTIPLIER 3
#endif
