#ifndef AKIT_CONSTANTS_H
#define AKIT_CONSTANTS_H
#define AKIT_SAMPLE_RATE 44100
#define AKIT_FRAME_LENGTH 512
#define AKIT_CHANNELS 2
#define AKIT_MAX_SOUNDS 24
#define AKIT_MAX_SOUND_LENGTH 60
#define AKIT_TAPE_LENGTH_MULTIPLIER 3

#define AKIT_DSP_SAMPLE_TARGET 1.0f
#define AKIT_MAX_SAMPLE 1.01f
#define AKIT_MIN_SAMPLE -AKIT_MAX_SAMPLE
#define AKIT_DSP_SAMPLE_ERROR_TOLERANCE 0.1f
#define AKIT_DSP_SILENCE 0.000001f
#define AKIT_DSP_GAIN_SILENCE 0.0001f

#define AKIT_DRIVER_TIMEOUT 5000


#define AKIT_FFT_SCOPE (128)
#define AKIT_FFT_SIZE (AKIT_SAMPLE_RATE)

#define AKIT_CLIPS_PER_TRACK 16

#endif
